#!/usr/bin/env python
from gmusicapi import Musicmanager
mm = Musicmanager()
if not mm.login():
    try:
        mm.perform_oauth()
    except e:
        print "Unable to perform OAuth", e
        exit()
    mm.login()
import sys
print "Uploading file:", sys.argv[1]
mm.upload(sys.argv[1])

